### PR TITLE
Rename GeterateIdString -> GenerateIDString

### LINKED ISSUE #260: Typo in method name GeterateIdString
#### Broken rules:

The method name has a typo in it `GeterateIdString` should be changed to `GenerateIdString` as identified in https://github.com/BHoM/GSA_Toolkit/pull/259#pullrequestreview-1007712115

#### Suggestions to restore compliance:

Update method name.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #260 

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Review by travispotterBH — APPROVED** [review]
Pretty small changes. Makes sense.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Review by IsakNaslundBh — APPROVED** [review]
Only name change of internal method. If Bot is able to pass all checks and compile, I am fine with this going in.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
