### PR TITLE
Pull timber material from gsa 10 wrong value

### LINKED ISSUE #287: Pull timber material from GSA 10 wrong value
#### Description:

Shear modulus and thermal expansion coefficient values get swapped when you pull timber material from GSA 10.

### PR DESCRIPTION
**Pull request by johannaisak**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #287 

 
Shear modulus and thermal coefficient value fix - swapped indices

 ### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/GSA_Toolkit/%23288-pull-timber-material-from-gsa-10-wrong-value?csf=1&web=1&e=HMgtjQ

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Review by IsakNaslundBh — APPROVED** [review]
Happy with the changes.

Have tested with test script, which proves the changes are right.

ode changes are looking great as well.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
