### PR TITLE
GSA_Toolkit: Fix compliance

### LINKED ISSUE #151: Compliance issues
The following compliance issues have been found for this repository. Please see the checklist below.
#### Compliance issue for HasSingleClass
 - [ ] Files cannot contain more than one class in GSA_Toolkit\GSA_oM\Enums.cs at line 39, column 16 
 - [ ] Files cannot contain more than one class in GSA_Toolkit\GSA_oM\Enums.cs at line 47, column 16

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #151

 

@johannaisak this should have 0 functional change. COuld you check that things are still working as before.

@FraserGreenroyd adding you as CI checker 😉 

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
I am happy with the compliance fixes from CheckCompliance - I will leave for @johannaisak to provide approving review on a functionality basis.

**Comment by IsakNaslundBh** [comment]
Thanks @johannaisak

**Pull request merged**
