### PR TITLE
Fix project compliance relating to Adapter_oM

### LINKED ISSUE #266: Fix Adapter_oM Project compliance
#### Broken rules:

See check in https://github.com/BHoM/GSA_Toolkit/pull/244/checks?check_run_id=8595866469

#### Suggestions to restore compliance:

Fix the compliance as outlined by the check

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #266 

 

Fix compliance issue identified in https://github.com/BHoM/GSA_Toolkit/pull/244/checks?check_run_id=8595866469

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Review by johannaisak — APPROVED** [review]
LGTM

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
Have reviewed the code and am happy this meets compliance requirements

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
