### PR TITLE
Fix BarVaryingLoad distributions

### LINKED ISSUE #191: GSA_Toolkit: Fix BarVaryingLoad distributions
#### Description:

BHoM defines varying load with distances from startpoint and endpoint. GSA defines it with both distances meassured from the startpoint.

This is not correctly converted.

#### Expected behaviour:

Fix to put in place to handle when possible and raise errors when not handleable

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #191 

 

Fixes the distribution of loads to match the BHoM definition. Raising errors for cases that can not be easily resolved.
Also fixing type, updating from tri-linear to patch

 ### Test files

Issue test:
https://burohappold.sharepoint.com/:f:/s/BHoM/EiqHlJ1iFfhCm7I6iY6COdYBzOfQiV1gLmxbbW26_lwcSA?e=prY4df

General load tests:
https://burohappold.sharepoint.com/:f:/s/BHoM/EjE55YVx2IVCg3BjvBozJokB_1pz0ajFCnjmr8PN6m2few?e=wVX232

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by alelom** [comment]
All fine, except in this:
image
is the first a leftover empty Note?

**Review by alelom — DISMISSED** [review]
LGTM. 
See comment https://github.com/BHoM/GSA_Toolkit/pull/192#issuecomment-694405951

**Comment by IsakNaslundBh** [comment]
Thanks @alelom , had missed to fill in that comment 🤦 Have pushed a fix now, grateful for a re-review!

**Review by alelom — APPROVED** [review]
LGTM!

**Pull request merged**
