### PR TITLE
Add controls for setting residuals to be used for Non-linear tasks

### LINKED ISSUE #236: GSA_Toolkit: Add control of setting residual forces and moments for combinations

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #236 

 

Adding control over:
- Resdiual force and moment for non-linear combinations
- If BeamSlendernessEffect should be taken into account for non-linear combinations

Making Cases depend on combinations so that cases are pushed in when combinations are.

 ### Test files

Testscript pushing combinations with varied settings and also checking that pushing without fragment assigned works.

https://burohappold.sharepoint.com/:f:/s/BHoM/EgbK4bHB-kxIr4wiRKXyON8BB0tUUQZvA-k2grsaKk22gg?e=GSzSRN

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance

**Review by johannaisak — DISMISSED** [review]
Works as expected!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check project-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance

**Review by johannaisak — APPROVED** [review]
Reapproving

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
