### PR TITLE
Pull Form Finding Properties

### LINKED ISSUE #294: Pull form finding properties
#### Description:

Add functionality to pull form finding properties. It is currently possible to push these, but not pull.

### PR DESCRIPTION
**Pull request by TosteSkDa**
Added new functionality to pull form finding properties (Soap Stress 1D and Soap Stress 2D).

 ### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #294 

 

 ### Test files

https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&web=1&e=qBkOOh&cid=ac585af7%2Deee7%2D427f%2Dad7d%2D58e55a61714b&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FGSA%5FToolkit%2F%23294%2DPull%20form%20finding%20properties&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Review by johannaisak — DISMISSED** [review]
Works as expected and code looks good!

**Comment by johannaisak** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by johannaisak — APPROVED** [review]
Reapproving after updating assembly references

**Comment by johannaisak** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
